Feature: JWT generate and verify helpers
pylover/miniutils pull request #1
Opened 2023-09-02 07:19 UTC by hosseinsokhandan

Please take a detailed look at the following concepts in my code, I need your attention there:

- printf mechanism I used for output response. (Is it a good idea to use stdout as output)
- subcommand functionality.
- memory efficiency (I have some variable definitions in helpers body)

2023-09-02 07:19 UTC, hosseinsokhandan commented
I hate it does not have tests!!

2023-09-02 13:49 UTC, pylover requested changes

2023-09-02 13:49 UTC, pylover commented on jwt.c
> +error_t parse_opt(int key, char *arg, struct argp_state *state) {
```c
static error_t
parse_opt ....
```

2023-09-02 13:49 UTC, pylover commented on jwt.c
> +        return -1;
```C
ERROR("Invalid command: %s", command);
```

2023-09-03 11:50 UTC, pylover approved these changes

2023-09-03 11:50 UTC, merged